"""Export a memo to Markdown, JSON, styled HTML, and XLSX.

Local-first product surface (ADR-0009): the deliverables are files, not a web
app. HTML is self-contained and print-to-PDF ready in any browser.
"""
from __future__ import annotations

import html
from pathlib import Path

from .memo import render_markdown
from .metrics import METRIC_KEYS
from .models import Memo

# metrics that are fractions (render as percentages)
_PCT = {"ann_return", "ann_vol", "max_drawdown", "downside_dev", "alpha", "tracking_error", "hit_rate"}


def _pct(x):
    return "n/a" if x is None else f"{x * 100:.1f}%"


def _num(x):
    return "n/a" if x is None else f"{x:.2f}"


def write_markdown(memo: Memo, path: str | Path) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render_markdown(memo))
    return p


def write_json(memo: Memo, path: str | Path) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(memo.model_dump_json(indent=2))
    return p


_CSS = """
:root{--bg:#0A1628;--panel:#0e1e35;--line:#1c3350;--teal:#00E5C4;--txt:#dfe9f5;--dim:#7f97b5;}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--txt);font:15px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;padding:40px}
.wrap{max-width:920px;margin:0 auto}
h1{font-size:26px;margin:0 0 6px;letter-spacing:.3px}
.meta{color:var(--dim);font-size:13px;margin-bottom:4px}
.badge{display:inline-block;padding:3px 10px;border:1px solid var(--teal);color:var(--teal);border-radius:999px;font-size:12px;font-weight:600}
.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
table{width:100%;border-collapse:collapse;margin:18px 0;font-size:13px}
th,td{padding:8px 10px;border-bottom:1px solid var(--line);text-align:right}
th:first-child,td:first-child,th:nth-child(2),td:nth-child(2){text-align:left}
thead th{color:var(--teal);text-transform:uppercase;font-size:11px;letter-spacing:.6px}
.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:20px 22px;margin:16px 0;box-shadow:0 0 24px rgba(0,229,196,.04)}
.card h2{margin:0 0 10px;font-size:17px}
.claims{margin-top:12px;padding-top:12px;border-top:1px solid var(--line);display:flex;flex-wrap:wrap;gap:8px}
.chip{font-size:12px;padding:4px 10px;border-radius:8px;background:#0b2033;border:1px solid var(--line)}
.chip.ok{border-color:rgba(0,229,196,.5)}
.chip.warn{border-color:#e5a100;color:#ffcf66}
.foot{color:var(--dim);font-size:12px;margin-top:28px;border-top:1px solid var(--line);padding-top:12px}
"""


def render_html(memo: Memo) -> str:
    e = html.escape
    a = memo.audit
    rows = []
    for s in memo.shortlist:
        m = s.metrics
        rows.append(
            f"<tr><td>{s.rank}</td><td>{e(s.name)}</td><td>{e(s.strategy)}</td>"
            f"<td class='mono'>{_pct(m.get('ann_return'))}</td><td class='mono'>{_num(m.get('sharpe'))}</td>"
            f"<td class='mono'>{_num(m.get('sortino'))}</td><td class='mono'>{_num(m.get('calmar'))}</td>"
            f"<td class='mono'>{_pct(m.get('max_drawdown'))}</td></tr>"
        )
    cards = []
    for sec in memo.sections:
        chips = ""
        if sec.claims:
            cs = []
            for c in sec.claims:
                cls = "ok" if c.verified else "warn"
                src = e("; ".join(c.source_refs) or "no source")
                cs.append(f"<span class='chip {cls}' title='{src}'>{'✓' if c.verified else '⚠'} {e(c.text)}</span>")
            chips = f"<div class='claims'>{''.join(cs)}</div>"
        cards.append(f"<div class='card'><h2>{e(sec.heading)}</h2><div>{e(sec.body)}</div>{chips}</div>")
    return (
        f"<!doctype html><html><head><meta charset='utf-8'><title>{e(memo.title)}</title>"
        f"<style>{_CSS}</style></head><body><div class='wrap'>"
        f"<h1>{e(memo.title)}</h1>"
        f"<div class='meta'>Mandate: {e(memo.mandate)} &nbsp;·&nbsp; Generated by <span class='mono'>{e(memo.generated_by)}</span> &nbsp;·&nbsp; {e(memo.version)}</div>"
        f"<div class='meta'><span class='badge'>{a.get('verified_count',0)}/{a.get('claim_count',0)} claims verified</span></div>"
        f"<table><thead><tr><th>#</th><th>Fund</th><th>Strategy</th><th>Ann.Return</th><th>Sharpe</th><th>Sortino</th><th>Calmar</th><th>MaxDD</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table>"
        f"{''.join(cards)}"
        f"<div class='foot'>AllocatorMemoBuilder · every figure traces to a source row + formula · print to PDF from your browser</div>"
        f"</div></body></html>"
    )


def write_html(memo: Memo, path: str | Path) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render_html(memo))
    return p


def write_xlsx(memo: Memo, ctx, path: str | Path) -> Path:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill

    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    wb = Workbook()
    head_fill = PatternFill("solid", fgColor="0A1628")
    head_font = Font(bold=True, color="00E5C4")

    def style_header(ws, ncols):
        for c in range(1, ncols + 1):
            cell = ws.cell(row=1, column=c)
            cell.fill = head_fill
            cell.font = head_font

    # Shortlist
    ws = wb.active
    ws.title = "Shortlist"
    cols = ["rank", "fund_id", "name", "strategy", "score", "ann_return", "sharpe", "sortino", "calmar", "max_drawdown", "ann_vol"]
    ws.append([c.replace("_", " ").title() for c in cols])
    for s in memo.shortlist:
        m = s.metrics
        ws.append([s.rank, s.fund_id, s.name, s.strategy, s.score,
                   m.get("ann_return"), m.get("sharpe"), m.get("sortino"),
                   m.get("calmar"), m.get("max_drawdown"), m.get("ann_vol")])
    style_header(ws, len(cols))

    # All-funds metrics
    ws2 = wb.create_sheet("Metrics")
    hdr = ["fund_id", "name"] + METRIC_KEYS
    ws2.append([h.replace("_", " ").title() for h in hdr])
    for fid, vals in ctx.metrics_by_fund.items():
        f = ctx.get_fund(fid)
        ws2.append([fid, f.name if f else fid] + [vals.get(k) for k in METRIC_KEYS])
    style_header(ws2, len(hdr))
    for ci, k in enumerate(hdr):
        if k in _PCT:
            for r in range(2, ws2.max_row + 1):
                ws2.cell(row=r, column=ci + 1).number_format = "0.0%"

    # Audit trail
    ws3 = wb.create_sheet("Audit")
    ws3.append(["fund_id", "metric", "value", "verified", "sources"])
    for c in memo.audit.get("claims", []):
        ws3.append([c.get("fund_id"), c.get("metric"), c.get("value"), c.get("verified"), "; ".join(c.get("sources", []))])
    style_header(ws3, 5)

    wb.save(p)
    return p


def export_all(memo: Memo, ctx=None, outdir: str | Path = "exports") -> dict:
    paths = {
        "md": write_markdown(memo, Path(outdir) / "memo.md"),
        "json": write_json(memo, Path(outdir) / "memo.json"),
        "html": write_html(memo, Path(outdir) / "memo.html"),
    }
    if ctx is not None:
        paths["xlsx"] = write_xlsx(memo, ctx, Path(outdir) / "memo.xlsx")
    return paths
